spring.application.name=novadesk-api

spring.datasource.url=jdbc:h2:mem:novadesk
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
